services:
  fragly_db:
    image: postgres:17
    restart: always
    container_name: fragly_pg
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: cs2
    ports:
      - "5434:5432"
    volumes:
      - fragly_pg_data:/var/lib/postgresql/data
    networks:
      - fragly

volumes:
  fragly_pg_data:

networks:
  fragly:
