version: '3.8'

services:
  fragly_db:
    image: postgres:17-alpine
    restart: always
    container_name: fragly_pg
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: cs2
    ports:
      - "5434:5432"
    volumes:
      - fragly_pg_data:/var/lib/postgresql/data
    networks:
      - fragly

  fragly_redis:
    image: redis:7-alpine
    restart: always
    container_name: fragly_redis
    ports:
      - "6379:6379"
    volumes:
      - fragly_redis_data:/data
    networks:
      - fragly

volumes:
  fragly_pg_data:
  fragly_redis_data:

networks:
  fragly:
    driver: bridge